[bell]
animation = "EaseOutExpo"
color = "#ffffff"
duration = 0

[colors]
draw_bold_text_with_bright_colors = false

[colors.bright]
black = "#504945"
blue = "#83a598"
cyan = "#8ec07c"
green = "#b8bb26"
magenta = "#d3869b"
red = "#fb4934"
white = "#f9f5d7"
yellow = "#fabd2f"

[colors.dim]
black = "#131415"
blue = "#556a7d"
cyan = "#5b7d78"
green = "#777c44"
magenta = "#75617b"
red = "#864343"
white = "#828482"
yellow = "#9e824c"

[colors.normal]
black = "#282828"
blue = "#458588"
cyan = "#689d6a"
green = "#98971a"
magenta = "#b16286"
red = "#cc241d"
white = "#ebdbb2"
yellow = "#d79921"

[colors.primary]
background = "#1d1f21"
foreground = "#c5c8c6"

[env]
TERM = "alacritty"

[font]
size = 8

[font.glyph_offset]
x = 0
y = 0

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 0

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Shift|Control"

[[keyboard.bindings]]
action = "Copy"
key = "Copy"
mods = "Shift|Control"

[[keyboard.bindings]]
action = "ScrollPageUp"
key = "PageUp"

[[keyboard.bindings]]
action = "ScrollPageDown"
key = "PageDown"

[[keyboard.bindings]]
action = "ScrollToTop"
key = "Home"

[[keyboard.bindings]]
action = "ScrollToBottom"
key = "End"

[scrolling]
history = 2000
multiplier = 3

[window]
decorations = "full"
opacity = 0.9
startup_mode = "Windowed"
title = "Alacritty"

[window.dimensions]
columns = 140
lines = 45

[window.padding]
x = 0
y = 0
